Models/PaymentStructure.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;

namespace DSRCManagementSystem.Models
{
    public class PaymentStructure
    {
        public string groupicon { get; set; }
        public string CustomerName { get; set; }
        public string UserName { get; set; }
        public int? Userid { get; set; }
        public string Branch { get; set; }
        public int? BranchId { get; set; }
        public int? DepartmentId { get; set; }
        public int? GroupId { get; set; }
        public string Department { get; set; }
        public string Group { get; set; }
        public string CreatedBy { get; set; }
        public int StatusID { get; set; }
        public string Status { get; set; }
        public string PaymentType { get; set; }
        public string comments { get; set; }
        public int PaymentTypeID { get; set; } 
        public int? PaymentID { get; set; }
        public int PaymentTermID { get; set; }
        public double Amount { get; set; }
        public double? PaidAmount { get; set; }
        public double? PendingAmount { get; set; }
        public double AdditionalAmount { get; set; }
        public double OverAllAmount { get; set; }
        public double MonthlyAmount { get; set; }
        public double YearlyAmount { get; set; }
        public DateTime MonthlyDueDate { get; set; }
        public DateTime YearlyDueDate { get; set; }
        public DateTime DueDate { get; set; }
        public List<string> TermAmount { get; set; }
        //public List<string> TotalTermAmount { get; set; }
        //public List<string> TotalTermDueDate { get; set; }
        public string TotalTermAmount { get; set; }
        public string TotalTermDueDate { get; set; }
        public string TotalTaxType { get; set; }
        public string TotalTaxAmount { get; set; }
        public List<string>MonthlyAdditionalAmount { get; set; }
        public List<string> YearlyAdditionalAmount { get; set; }
        public List<string> TermAdditionalAmount { get; set; }
        public List<PaymentStructure> Employeedetails { get; set; }
        public List<string> UserList { get; set; }
        public int dbvalue { get; set; }

    }

    
    public class UpdatePaymentStructure
    {
        public string CustomerName { get; set; }
        public string UserName { get; set; }
        public int? Userid { get; set; }
        public string Branch { get; set; }
        public int? BranchId { get; set; }
        public int? DepartmentId { get; set; }
        public int? GroupId { get; set; }
        public string Department { get; set; }
        public string Group { get; set; }
        public string CreatedBy { get; set; }
        public int StatusID { get; set; }
        public string Status { get; set; }
        public string PaymentType { get; set; }
        public string comments { get; set; }
        public int PaymentTypeID { get; set; }
        public int? PaymentID { get; set; }
        public int PaymentTermID { get; set; }
        public double Amount { get; set; }
        public double? PaidAmount { get; set; }
        public double? PendingAmount { get; set; }
        public double AdditionalAmount { get; set; }
        public double OverAllAmount { get; set; }
        public double MonthlyAmount { get; set; }
        public double YearlyAmount { get; set; }
        public DateTime MonthlyDueDate { get; set; }
        public DateTime YearlyDueDate { get; set; }
        public DateTime DueDate { get; set; }
        public List<string> TermAmount { get; set; }
        //public List<string> TotalTermAmount { get; set; }
        //public List<string> TotalTermDueDate { get; set; }
        public string TotalTermAmount { get; set; }
        public string TotalTermDueDate { get; set; }
        public string TotalTaxType { get; set; }
        public string TotalTaxAmount { get; set; }
        public List<string> MonthlyAdditionalAmount { get; set; }
        public List<string> YearlyAdditionalAmount { get; set; }
        public List<string> TermAdditionalAmount { get; set; }

    }
    public class FilterCustomer
    {
        public int PaymentId { get; set; }
        public string CustomerName { get; set; }
        public int? DepartmentId { get; set; }
        public int? GroupId { get; set; }
    }
    static class ext
    {

        internal static List<Variance> DetailedCompare(UpdatePaymentStructure updated, PaymentStructure saved)
        {
            List<Variance> variances = new List<Variance>();
            var prop = updated.GetType().GetProperties();
            var prop1 = saved.GetType().GetProperties().Select(x => x.Name);
            prop = prop.Where(x => prop1.Contains(x.Name)).ToArray();
            foreach (PropertyInfo f in prop)
            {
                Variance v = new Variance();

                if (f.Name == "RoleName")
                    v.FieldName = "Role Name";
                else if (f.Name == "Marital")
                    v.FieldName = " Marital Status";
                else
                    v.FieldName = f.Name;

                v.UserUpdateValue = updated.GetType().GetProperty(f.Name).GetValue(updated, null);
                v.UserSaveValue = saved.GetType().GetProperty(f.Name).GetValue(saved, null);
                //if (f.Name == "TotalTermAmount" || f.Name == "TotalTermDueDate")
                //{
                //    if (updated.TotalTermAmount != null && updated.TotalTermDueDate != null &&
                //        saved.TotalTermAmount != null && saved.TotalTermDueDate != null)
                //    {
                //        string[] old = updated.TermAmount.ToArray();
                //        string[] upda = saved.TermAmount.ToArray();
                //        foreach (var a in old)
                //        {
                //            if (!(upda).Contains(a))
                //            {
                //                variances.Add(v);
                //            }
                //        }
                //    }
                //}

                if (v.UserUpdateValue != null && v.UserSaveValue != null)
                {
                    if (!v.UserUpdateValue.ToString().SequenceEqual(v.UserSaveValue.ToString()))
                        //if (!v.UserUpdateValue.ToString().Equals(v.UserSaveValue.ToString()))
                            variances.Add(v);
                    
                }
                
                else
                {
                    if (v.UserUpdateValue == null && v.UserSaveValue == null)
                    {
                    }
                    else
                    {
                        variances.Add(v);
                    }
                }

            }
            return variances;
        }
    }

}

Controllers/PaymentStructureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DSRCManagementSystem.Models;
using System.Web.Configuration;
using System.Threading.Tasks;
using DSRCManagementSystem.DSRCLogic;

namespace DSRCManagementSystem.Controllers
{
    public class PaymentStructureController : Controller
    {
        DSRCManagementSystemEntities1 db = new DSRCManagementSystemEntities1();
        private static TimeZoneInfo INDIAN_ZONE = TimeZoneInfo.FindSystemTimeZoneById("India Standard Time");
        DsrcMailSystem.MailSender AppValue = new DsrcMailSystem.MailSender(); 
        public ActionResult ProjectPayment()
        {
            DateTime Today = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, INDIAN_ZONE);
            var CurMonth = Today.Month;
            var Curyear = Today.Year;
            var startDate = new DateTime(Curyear, CurMonth, 01);
            var endDate = new DateTime(Curyear, CurMonth, 01).AddMonths(1).AddSeconds(-1);
            List<PaymentStructure> obj = new List<PaymentStructure>();
           
            obj = (from p in db.ProjectPayments.Where(x => x.IsActive == true)
                   join s in db.Master_ProjectPaymentTerms on p.TermType equals s.ProjectPaymentTermID
                   select new PaymentStructure
                   {
                       PaymentID = p.PaymentID,
                       CustomerName = p.CustomerName,
                       PaymentType = s.Terms,
                       Amount = (double)p.Amount,
                   }).ToList();
            return View(obj);
        }

        [HttpGet]
        public ActionResult CreateProjectPayment()
        {
            ViewBag.Lbl_branch = CommonLogic.getLabelName(1).ToString();
            ViewBag.Lbl_department = CommonLogic.getLabelName(2).ToString();
            ViewBag.Lbl_depgroup = CommonLogic.getLabelName(3).ToString();
            var BranchList = db.Master_Branches.ToList();
            //var DepartmentList = db.Departments.Where(d => d.IsActive == true).ToList();
            var DepartmentList = communicationHelper.GetDepartments();

            var GroupList = db.DepartmentGroups.Where(d => d.IsActive == true).ToList();

            ViewBag.BranchList = new SelectList(new[] { new Master_Branches() { BranchID = 0, BranchName = "---Select---" } }.Union(BranchList), "BranchID", 

"BranchName", 0);
            ViewBag.DepartmentIdList = new SelectList(new[] { new Department() { DepartmentId = 0, DepartmentName = "---Select---" } }, "DepartmentId", 

"DepartmentName", 0);
            ViewBag.Groups = new SelectList(new[] { new DepartmentGroup() { GroupID = 0, GroupName = "---Select---" } }, "GroupID", "GroupName", 0);
            var PaymentType = (from p in db.Master_ProjectPaymentTerms
                               select new
                                  {
                                      PaymentTypeId = p.ProjectPaymentTermID,
                                      PaymentType = p.Terms
                                  }).ToList();
            ViewBag.PaymentType = new SelectList(PaymentType, "PaymentTypeId", "PaymentType");
            var TaxTypes = (from data in db.Master_ProjectPaymentTaxType
                            select new
                                {
                                    ProjectPaymentTaxTypeID = data.ProjectPaymentTaxTypeID,
                                    TaxType = data.TaxType
                                }).ToList();

            ViewBag.TaxTypes = new SelectList(TaxTypes,"ProjectPaymentTaxTypeID", "TaxType" );
            ViewData["TaxType"] = TaxTypes.Count();
            return View();
        }

        [HttpPost]
        public ActionResult CreateProjectPayment(PaymentStructure data)
        {
            string ServerName = AppValue.GetFromMailAddress("ServerName");
            try
            {
                if (TempData["Values"] != null)
                {


                }


                int userId = int.Parse(Session["UserID"].ToString());
                var Payment = db.ProjectPayments.CreateObject();
               
                Payment.CustomerName = data.CustomerName;
                Payment.TermType = data.PaymentTypeID;
               // Payment.Branch = data.BranchId;
               // Payment.Department = data.DepartmentId;
               // Payment.DepartmentGroup = data.GroupId;
                if (data.PaymentTypeID == 1)
                {
                    Payment.Amount = data.OverAllAmount + (data.MonthlyAmount * 11);
                }
                else
                {
                    Payment.Amount = data.OverAllAmount;
                }
                Payment.IsActive = true;
                db.ProjectPayments.AddObject(Payment);
                db.SaveChanges();
                int PaymentID = Payment.PaymentID;
                List<int> Users = null;
                if (data.GroupId == 0)
                {
                    Users =
                        db.Users.Where(
                            x =>
                                x.IsActive == true && x.BranchId == data.BranchId && x.DepartmentId == data.DepartmentId)
                            .Select(o => o.UserID).ToList();
                }
                else if (data.GroupId != 0)
                {
                    Users =
                      db.Users.Where(
                          x =>
                              x.IsActive == true && x.BranchId == data.BranchId && x.DepartmentId == data.DepartmentId && x.DepartmentGroup==data.GroupId)
                          .Select(o => o.UserID).ToList();
                }
                if (data.PaymentTypeID == 1)
                {
                    if (data.MonthlyAdditionalAmount != null)
                    {

                        foreach (string Amount in data.MonthlyAdditionalAmount)
                        {
                            if (Amount != "   --Select--                             ,")
                            {
                                if (Amount != "   --Select--   ,")
                                {
                                    var SplittedAmount = Amount.Split(',');
                                    string AdditionalTaxName = SplittedAmount[0].Trim();
                                    int AdditionalTaxID =
                                        db.Master_ProjectPaymentTaxType.FirstOrDefault(
                                            x => x.TaxType.Equals(AdditionalTaxName)).ProjectPaymentTaxTypeID;
                                    double AdditionalAmount = Convert.ToDouble(SplittedAmount[1]);
                                    db.ProjectPaymetTaxDetails.AddObject(new ProjectPaymetTaxDetail
                                    {
                                        PaymentID = PaymentID,
                                        AddionalTaxID = AdditionalTaxID,
                                        Amount = AdditionalAmount,
                                    });
                                }
                            }
                        }
                        db.SaveChanges();
                    }
                    DateTime duedate = (DateTime) data.MonthlyDueDate.AddMonths(-1);
                        for (int i = 1; i <= 12; i++)
                        {
                            if (Users.Count() > 0)
                            {
                                foreach (var user in Users)
                                {
                                    db.ProjectPaymetTermDetails.AddObject(new ProjectPaymetTermDetail
                                    {
                                        PaymentID = PaymentID,
                                        DueDate = duedate.AddMonths(i),
                                        Amount = data.MonthlyAmount,
                                        PaidStatus = 2,
                                        UserId = user,
                                    });
                                }
                            }
                            else
                            {
                              
                                    db.ProjectPaymetTermDetails.AddObject(new ProjectPaymetTermDetail
                                    {
                                        PaymentID = PaymentID,
                                        DueDate = duedate.AddMonths(i),
                                        Amount = data.MonthlyAmount,
                                        PaidStatus = 2,
                                       
                                    });
                                

                            }
                            db.SaveChanges();
                        }
                }
                else if (data.TermAmount != null)
                {
                    foreach (string Amount in data.TermAmount)
                    {
                        var SplittedAmount = Amount.Split(',');
                        //string TermAmount = SplittedAmount[0].Trim();

                        double TermAmount = Convert.ToDouble(SplittedAmount[0]);
                        DateTime duedate = Convert.ToDateTime(SplittedAmount[1].ToString());
                        if (Users.Count() != 0)
                        {
                            foreach (var user in Users)
                            {
                                db.ProjectPaymetTermDetails.AddObject(new ProjectPaymetTermDetail
                                {
                                    PaymentID = PaymentID,
                                    DueDate = duedate,
                                    Amount = TermAmount,
                                    PaidStatus = 2,
                                    UserId = user
                                });
                            }
                        }
                        else
                        {

Views/PaymentStructure/AssignPaymentGroup.cshtml
@model DSRCManagementSystem.Models.PaymentStructure
@{
    ViewBag.Title = "Create Task";
    Layout = null;
}
<!Doctype html>
<html>
    <head>
    <meta name="viewport" content="width=device-width" />
    <title>Create Task</title>

    <link href="../../Content/Template/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" type="text/css" />
    <link href="../../Content/Template/css/font-icons/entypo/css/entypo.css" rel="stylesheet" type="text/css" />
    <script src="../../Content/Template/js/select2/select2.min.js" type="text/javascript"></script>
    <link href="../../Content/Template/js/select2/select2-bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="../../Content/Template/js/select2/select2.css" rel="stylesheet" type="text/css" />
    <script src="../../Content/Template/js/toastr.js" type="text/javascript"></script>
    <script src="../../Content/JS/ToasterAlert.js" type="text/javascript"></script>
    <script src="../../Content/Template/js/bootstrap-datepicker.js" type="text/javascript"></script>

         <style>
        .dropdown-menu {
    background-color: white;
}
        </style>

    </head>
    <body>
       
    <div class="modal-content">
        <div class="modal-header" style="background-color: #f0f0f1;">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×</button>
            <h4 class="modal-title">
                Assign Payment Group</h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("AssignPaymentGroup", "PaymentStructure"))
            {  
                <div class="row">
                    <div class="col-md-12" style="text-align: right">
                        @Html.Label("*", new { @style = "color:#FF0000" }) Required field(s)
                    </div>
                </div>
                
                   <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                         @Html.Label("Customer Name", new { @class = "control-label" })    
                         @Html.TextBoxFor(x => x.CustomerName, new { @id = "CustomerName", @name = "CustomerName", @class = "form-control", @style = "height:45px", @readonly = "readonly" })                                                                      
                          <span id="span_Desc" style="color: Red;"></span>    
                      </div>
                      </div>
                        <div class="col-md-6">
                      <div class="form-group">
                         @Html.Label("Branch",(string)ViewBag.Lbl_branch, new { @class = "control-label" })  
                         @Html.Label("*", new { @style = "color:#FF0000" })   
                         @Html.DropDownListFor(x => x.Branch, ViewBag.BranchList as SelectList, new
                           {
                               @id = "Idbranchname",
                               @name = "BranchName",
                               @class = "form-control",
                               @onchange = "GetDepartments()"
                           })
                          <span id="span_Branch" style="color: Red;"></span>    
                      </div>
                      </div>
                   </div>
                 <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                         @Html.Label("Department Name",(string)ViewBag.Lbl_department, new { @class = "control-label" })  
                          @Html.Label("*", new { @style = "color:#FF0000" })   
                           @Html.DropDownListFor(x => x.Department, ViewBag.DepartmentIdList as SelectList, new
                           {
                               @id = "Iddepartment",
                               @name = "DepartmentId",
                               @class = "form-control",
                               @onchange = "GetGroups()"
                           })
                          <span id="span_Department" style="color: Red;"></span>    
                      </div>
                      </div>
                        <div class="col-md-6">
                      <div class="form-group">
                         @Html.Label("Group",(string)ViewBag.Lbl_depgroup , new { @class = "control-label" })  
                          @Html.Label("*", new { @style = "color:#FF0000" })   
                           @Html.DropDownListFor(x => x.Group, ViewBag.Groups as SelectList, new
                                    {
                                        @id = "Idgroup",
                                        @name = "Group",
                                        @class = "form-control",
                                    })
                          <span id="span_Group" style="color: Red;"></span>   
                      </div>
                      </div>
                   </div>
                 <div class="row">
                    <div class="col-md-12">
                         <span id="span_RecurringDesc" style="color:green;"></span> 
                    </div>
                </div>
            }
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
                Cancel
            </button>
            <button type="button" id="btnAdd" class="btn btn-info" onclick="AssignGroup(@ViewBag.PaymentId)">
                Save
            </button>

        </div>
    </div>
      <script type="text/javascript">
          $(function () {
              $("#StartDateTime").val('');
              $(".datetimepicker").datepicker({
                  format: 'yyyy-mm-dd',
                  todayHighlight: true,
                  autoclose: true,
                  startDate: '1d'
              });
          });
          $(function () {

              $(".modal-body select").select2({
                  minimumResultsForSearch: -1
              });

              $("#ReportingUsers").select2();
          });
          function GetDepartments() {

              var Bid = $("#Idbranchname").find("option:selected").prop("value");

              if (Bid !== "") {

                  var url2 = '@Url.Action("GetDepartments","Users")';

                $.get(url2, { BranchId: Bid }, function (data) {

                    var items = [];
                    items.push("");
                    items.push("<option value=0>---Select---</option>");

                    $.each(data, function () {
                        items.push("<option value=" + this.Value + ">" + this.Text + "</option>");
                    });
                    $("#Iddepartment").html(items.join(' '));
                    $("#Iddepartment").select2();
                });
            }
        }
        function GetGroups() {

            var Did = $("#Iddepartment").find("option:selected").prop("value");

            if (Did !== "") {

                var url2 = '@Url.Action("GetGroups", "Users")';

                $.get(url2, { DepartmentId: Did }, function (data) {

                    var items = [];
                    items.push("");
                    items.push("<option value=0>---Select---</option>");

                    $.each(data, function () {
                        items.push("<option value=" + this.Value + ">" + this.Text + "</option>");
                    });
                    $("#Idgroup").html(items.join(' '));
                    $("#Idgroup").select2();
                });
            }
        }
          var opts = {
              "closeButton": true,
              "debug": false,
              "positionClass": "toast-top-right",
              "onclick": null,
              "showDuration": "300",
              "hideDuration": "1000",
              "timeOut": "2000",
              "extendedTimeOut": "1000",
              "showEasing": "swing",
              "hideEasing": "linear",
              "showMethod": "fadeIn",
              "hideMethod": "fadeOut"
          };
          function AssignGroup(PaymentId) {

              var value = {
                  "PaymentID": PaymentId,
                  "BranchId": $("#Idbranchname").val(),
                  "DepartmentId": $("#Iddepartment").val(),
                  "GroupId": $("#Idgroup").val()
              };
              var Branch = $("#Idbranchname").val();
              var Department = $("#Iddepartment").val();
              var Group = $("#Idgroup").val();
              if (Branch == '0' || Department == '0' || Group == '0') {
                  if (Branch == '0')
                      document.getElementById("span_Branch").innerHTML = "Select Branch";
                  else
                      document.getElementById("span_Branch").innerHTML = "";
                  if (Department == '0')
                      document.getElementById("span_Department").innerHTML = "Select Department";
                  else
                      document.getElementById("span_Department").innerHTML = "";
                  if (Group == '0')
                      document.getElementById("span_Group").innerHTML = "Select Group";
                  else
                      document.getElementById("span_Group").innerHTML = "";
              }
              else {
                  $.ajax({
                      url: "../../PaymentStructure/AssignPaymentGroup/",
                      type: 'POST', cache: false,
                      data:value,
                      success: function (result) {
                          if (result == "success") {
                              toastr.success("Payment Assigned to Group Successfully", opts);
                              $("#portlet-config").modal('hide');
                              setTimeout(function () { location.reload(); }, 1000);
                          }
                          else {
                              toastr.warning("Payment Assigning Failed", opts);
                              $("#portlet-config").modal('hide');
                              setTimeout(function () { location.reload(); }, 1000);
                          }
                      }

                  });
              }
          }
         
    </script>
   
    </body>
</html>