Models/AddVehicle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.Web.Mvc;

namespace DSRCManagementSystem.Models
{
    public class AddVehicle 
    {
        public int vehicleid { get; set; }
        public string Vehicle_No { get; set; }
        public string VehicleModel { get; set; }
        public int? VehicleModel_Id { get; set; }
        public int? VehicleBrand_Id { get; set; }
        public string VehicleBrand { get; set; }
        public int ?Model_Year{get;set;}
        public int ?No_of_Seat{get;set;}
        public int ?Trip{get;set;}
        public string Remarks{get;set;}
        public string VehicleType { get; set; }
        public int ?VehicleType_Id { get; set; }
        public long? Contact_No { get; set; }
        public string VehicleMake { get; set; }
        public string Vehicle_Photo { get; set; }
        public bool IsActive { get; set; }
        public string path { get; set; }
       
        public string DriverName { get; set; }
        public string Co_DriverName { get; set; }
    }
    //public class AddsVehicle
    //{
    //    public int vehicleid { get; set; }
    //    public string Vehicle_No { get; set; }
    //    public string VehicleModel { get; set; }
    //    public int? VehicleModel_Id { get; set; }
    //    public int? VehicleBrand_Id { get; set; }
    //    public string VehicleBrand { get; set; }
    //    public int? Model_Year { get; set; }
    //    public int? No_of_Seat { get; set; }
    //    public int? Trip { get; set; }
    //    public string Remarks { get; set; }
    //    public string VehicleType { get; set; }
    //    public int? VehicleType_Id { get; set; }
    //    public long? Contact_No { get; set; }
    //    public string VehicleMake { get; set; }
    //    public string Vehicle_Photo { get; set; }
    //    public bool IsActive { get; set; }

    //}
}

Models/Transportation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DSRCManagementSystem.Models
{
    public class Transportation
    {
        public int? Id { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleMake { get; set; }
        public  int ?YearsofManufacturing { get; set; }
        public string ExpenseType { get; set; }
        public int? Cost { get; set; }
        public int? ExpenseId { get; set; }
        public string date { get; set; }
        public DateTime? dateofyear { get; set; }
        public int? ManageExpenseId { get; set; }
    }
}

Controllers/TransportationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DSRCManagementSystem.Models;
using DSRCManagementSystem.DSRCLogic;
using System.Text;
using System.Reflection;
using Microsoft.Ajax.Utilities;
using System.Data.Linq.SqlClient;
namespace DSRCManagementSystem.Controllers
{
    public class TransportationController : Controller
    {
        //
        // GET: /Transportation/
        DSRCManagementSystemEntities1 objdb = new DSRCManagementSystemEntities1();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManageVehicle(string value)
        {
            DSRCManagementSystemEntities1 db = new DSRCManagementSystemEntities1();

            List<DSRCManagementSystem.Models.AddVehicle> objmodel = new List<Models.AddVehicle>();
            try
            {
                if (value == null)
                {
                    objmodel = (from c in db.Vehicles.Where(x => x.IsActive == true)
                                select new DSRCManagementSystem.Models.AddVehicle()
                               {

                                   vehicleid = c.VehicleId,
                                   Vehicle_No = c.Vehicle_No,
                                   VehicleMake = c.VehicleMake,
                                   VehicleModel_Id = c.VehicleModel_Id
                               }).ToList();



                    var number = (from p in db.Vehicles.Where(x => x.IsActive == true)
                                  select new DSRCManagementSystem.Models.AddVehicle()

                                  {
                                      vehicleid = p.VehicleId,
                                      Vehicle_No = p.Vehicle_No,

                                  }).ToList();
                    ViewBag.Vehicles = new SelectList(number, "Vehicleid", "Vehicle_No");
                }
                else
                {
                    objmodel = (from c in db.Vehicles.Where(x => x.IsActive == true && x.Vehicle_No == value)
                                select new DSRCManagementSystem.Models.AddVehicle()
                                {

                                    vehicleid = c.VehicleId,
                                    Vehicle_No = c.Vehicle_No,
                                    VehicleMake = c.VehicleMake,
                                    VehicleModel_Id = c.VehicleModel_Id
                                }).ToList();



                    var number = (from p in db.Vehicles.Where(x => x.IsActive == true)
                                  select new DSRCManagementSystem.Models.AddVehicle()

                                  {
                                      vehicleid = p.VehicleId,
                                      Vehicle_No = p.Vehicle_No,

                                  }).ToList();
                    ViewBag.Vehicles = new SelectList(number, "Vehicleid", "Vehicle_No");
                }
            }
            catch (Exception Ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                ExceptionHandlingController.ExceptionDetails(Ex, actionName, controllerName);

            }
            return View(objmodel);
        }






        [HttpGet]
        public ActionResult ManageExpense(string ExpenseId, string intexp)
        {
            DSRCManagementSystemEntities1 objdb = new DSRCManagementSystemEntities1();
            List<DSRCManagementSystem.Models.Transportation> objmodel = new List<DSRCManagementSystem.Models.Transportation>();
            int expid = 0;
            if (intexp != "")
            {
                expid = Convert.ToInt32(intexp);
            }

            var vehicles = (from p in objdb.Vehicles.Where(x => x.IsActive == true || x.IsActive == null)
                            select new
                            {
                                VehicleId = p.VehicleId,
                                VehicleNo = p.Vehicle_No,

                            }).Distinct().ToList();

            if (intexp == null || intexp == "")
            {
                ViewBag.Vehicles = new SelectList(vehicles.Distinct(), "VehicleId", "VehicleNo");
            }

            else
            {
                ViewBag.Vehicles = new SelectList(vehicles.Distinct(), "VehicleId", "VehicleNo", expid);
            }

            if (ExpenseId == null || intexp == "")
            {

                objmodel = (from p in objdb.Vehicles.Where(x => x.IsActive == true || x.IsActive == null)
                            join t in objdb.Master_VehicleModel on p.VehicleModel_Id equals t.VehicleModel_Id into y
                            from value in y.DefaultIfEmpty()
                            join v in objdb.ManageExpense_Mapping on p.VehicleId equals v.VehicleId into z
                            from abc in z.DefaultIfEmpty()
                            join x in objdb.ManageExpenses on abc.ManageExpenseId equals x.ManageExpenseId into value1 from abcd in value1.DefaultIfEmpty()
                           where abcd.Isactive == true
                            join c in objdb.Master_ExpenseType on abcd.ExpenseType equals c.ExpenseType_Id
                            select new DSRCManagementSystem.Models.Transportation
                            {
                                Id = p.VehicleId,
                                VehicleNumber = p.Vehicle_No,
                                VehicleModel = value.VehicleModel,
                                VehicleMake = p.VehicleMake,
                                ManageExpenseId = abc.ManageExpenseId,
                                //   ExpenseType = c.ExpenseType,
                                //Cost = abcd.Cost,
                                ExpenseId = abc.ManageExpenseId,
                                YearsofManufacturing = p.Model_Year
                            }).OrderByDescending(x => x.YearsofManufacturing).ToList();

                foreach (var item in objmodel)
                {
                    if (item.ManageExpenseId != null)
                    {
                        var values = objdb.ManageExpenses.Where(x => x.Isactive == true && x.ManageExpenseId == item.ManageExpenseId).Select(o => o).FirstOrDefault();
                        if (values != null)
                        {
                            var extype = objdb.Master_ExpenseType.Where(x => x.ExpenseType_Id == values.ExpenseType).Select(o => o.ExpenseType).FirstOrDefault();
                            if (extype != null)
                            {
                                item.ExpenseType = extype;
                            }
                            else
                            {
                                item.ExpenseType = null;
                            }
                            if (values.Cost != null)
                            {
                                item.Cost = values.Cost;
                            }
                            else
                            {
                                item.Cost = null;
                            }
                        }
                        else
                        {
                            item.ExpenseType = null;
                            item.Cost = null;

                        }
                    }
                    else
                    {
                        item.ManageExpenseId = null;
                        item.ExpenseType = null;
                        item.Cost = null;

                    }

                }


            }

            else
            {
                objmodel = (from p in objdb.Vehicles.Where(x => (x.IsActive == true || x.IsActive == null) && x.Vehicle_No == ExpenseId)
                            join t in objdb.Master_VehicleModel on p.VehicleModel_Id equals t.VehicleModel_Id into y
                            from value in y.DefaultIfEmpty()
                            join v in objdb.ManageExpense_Mapping on p.VehicleId equals v.VehicleId into z
                            from abc in z.DefaultIfEmpty()
                            join x in objdb.ManageExpenses on abc.ManageExpenseId equals x.ManageExpenseId into value1 from abcd in value1.DefaultIfEmpty()
                            where abcd.Isactive == true
                            join c in objdb.Master_ExpenseType on abcd.ExpenseType equals c.ExpenseType_Id
                            select new DSRCManagementSystem.Models.Transportation
                            {
                                Id = p.VehicleId,
                                VehicleNumber = p.Vehicle_No,
                                VehicleModel = value.VehicleModel,
                                VehicleMake = p.VehicleMake,
                                ManageExpenseId = abc.ManageExpenseId,
                                // ExpenseType = c.ExpenseType,
                                //Cost = abcd.Cost,
                                ExpenseId = abc.ManageExpenseId,
                                YearsofManufacturing = p.Model_Year
                            }).OrderByDescending(x => x.YearsofManufacturing).ToList();

                foreach (var item in objmodel)
                {
                    if (item.ManageExpenseId != null)
                    {
                        var values = objdb.ManageExpenses.Where(x => x.Isactive == true && x.ManageExpenseId == item.ManageExpenseId).Select(o => o).FirstOrDefault();
                        if (values != null)
                        {
                            var extype = objdb.Master_ExpenseType.Where(x => x.ExpenseType_Id == values.ExpenseType).Select(o => o.ExpenseType).FirstOrDefault();
                            if (extype != null)

Views/Transportation/AddExpense.cshtml
@model DSRCManagementSystem.Models.Transportation
@{
  
    Layout = null;
}

<!DOCTYPE html>
<html>


<head>
    <meta name="viewport" content="width=device-width" />
    <title>ProjectMeeting</title>

    <link href="../../Content/Template/css/font-icons/entypo/css/entypo.css" rel="stylesheet"
        type="text/css" /> 
         <script src="../../Content/Plugins/bootstrap-datetimepicker/js/moment.js" type="text/javascript"></script>
    
         <script src="../../Content/Template/js/select2/select2.min.js" type="text/javascript"></script>

    <script src="../../Content/Plugins/bootstrap-datetimepicker/js/en-gb.js" type="text/javascript"></script>
    <script src="../../Content/Plugins/bootstrap-datetimepicker/js/moment.js" type="text/javascript"></script>
    <script src="../../Content/Plugins/bootstrap-datetimepicker/js/bootstrap-datepicker.js"  type="text/javascript"></script>
    <style>
       .dropdown-menu {
    background-color: white;
}        
 </style> 

</head>

<body>
    <div class="modal-content">
        <div class="modal-header" style="background-color: #f0f0f1;">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×</button>
            <h4 class="modal-title">
             Add  Expense</h4>
        </div>
 
     <div class="modal-body">

            @using (Html.BeginForm("AddNewExpense", "Transportation", FormMethod.Post))
            {
                <div class="row">
                    <div class="col-md-12" style="text-align: right">
                        @Html.Label("*", new { @style = "color:#FF0000" }) Required field(s)
                       
                    </div>
                </div>
                
                 <div class="row" >

                   <div class="col-md-6">
                   <div class="form-group">
                @Html.Label("Vehicle Number", new { @class = "control-label" })
                @Html.Label("*", new { @style = "color:#FF0000" })
                @Html.DropDownList("VehicleId", ViewBag.Vehicles as SelectList, "--Select--", new { @id = "Number", @class = "form-control" })                   
                <span id="span_ID6" style="color: Red;"></span>
                   </div>
                </div> 
             
                
              
             
                    

                      <div class="col-md-6">  
                     <div class="form-group">
                      @Html.Label("Date", new { @class = "control-label" })    
                      @Html.Label("*", new { @style = "color:#FF0000" })              
                      @Html.TextBoxFor(x => x.YearsofManufacturing, new { @name = "Year", @id = "Year", @class = "form-control datetimepicker", @style = "Height:42Px", @maxlength = 50 }) 
                     <span id="span_ID9" style="color: Red;"></span>
                      </div>
                      </div>

                    

                
                </div> 
                 
              
                 <div class="row">
                   
                    <div class="col-md-6">  
                     <div class="form-group">
                      @Html.Label("Expense Type", new { @class = "control-label" })    
                      @Html.Label("*", new { @style = "color:#FF0000" })              
                      @Html.DropDownList("ExpenseId", ViewBag.Expense as SelectList, "--Select--", new { @id = "ExpenseType", @class = "form-control" })
                     <span id="span_ID10" style="color: Red;"></span>
                      </div>
                      </div>
                    




                       <div class="col-md-6">  
                     <div class="form-group">
                      @Html.Label("Cost", new { @class = "control-label" }) 
                       @Html.Label("*", new { @style = "color:#FF0000" })                 
                      @Html.TextBoxFor(x => x.Cost, new { @name = "Cost", @id = "Cost", @class = "form-control", @maxlength = 50, @style = "Height:42Px" }) 
                     <span id="span_ID11" style="color: Red;"></span>
                      </div>
                      </div>

                      </div>
                
        
                                 
                  <div class="row">
                     <div class="col-md-6">  
                     <div class="form-group">
                     
                      </div>
                      </div>

                      </div>
            }   

             </div>   
           
             <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
                Cancel
            </button>
            <button type="button" id="btnAdd" class="btn btn-info"  onclick='AddNewMeeting()' >
                Save
            </button>
        </div>
      </div>
                
     <div class="modal fade in" id="portlet-config1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="tools">
                <div id="PartialSection">
                    <div id="LoaderContent" style="height: 100%;">
                        <img src="../../Content/Template/images/finalloader.GIF" style="margin-left: 43%;
                            margin-top: 40%;" />
                    </div>
                </div>
            </div>
        </div>
    </div> 

    
   <script src="../../Content/Template/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="../../Content/Template/js/dataTables.bootstrap.js" type="text/javascript"></script>
    <script src="../../Content/Template/js/select2/select2.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/bootbox.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/js/bootstrap.js" type="text/javascript"></script>
    <script src="../../Content/Template/js/toastr.js" type="text/javascript"></script>
     <script src="../../Content/JS/ToasterAlert.js" type="text/javascript"></script>
          <script type="text/javascript">
              $(function () {
                  $(".modal-body select").select2({
                      minimumResultsForSearch: -1
                  });
                 
                  
              });

              $(".datetimepicker").datepicker({
                  format: 'dd/mm/yyyy',
                 // startDate: '-1d',
                  //daysOfWeekDisabled: [0, 6],
                  endDate: '1d',
                  autoclose: true
              });


              $(document).ready(function () {

                

                  $("#Cost").on('paste keypress', (function (e) {
                      var key;
                      if (e.which) {
                          key = String.fromCharCode(e.which);
                      } else {
                          key = e.originalEvent.clipboardData.getData('Text');
                      }
                      var value = $(this).val() + key;
                      if (!/^[0-9]{1,999}$/.test(value)) {
                          e.preventDefault();
                      }
                  }));


                  $("#Number").select2();
                  $("#ExpenseType").select2();

              });






              function AddNewMeeting() {

                
                  if (document.getElementById('Number').value == '' || document.getElementById('Number').value == null || document.getElementById('Year').value == '' || document.getElementById('Year').value == null || document.getElementById('ExpenseType').value == '' || document.getElementById('ExpenseType').value == null || document.getElementById('Cost').value == '' || document.getElementById('Cost').value == null) {

                      if (document.getElementById('Number').value == '' || document.getElementById('Number').value == null) {
                          document.getElementById("span_ID6").innerHTML = "Select vehicle number";
                      }
                      else {
                          document.getElementById("span_ID6").innerHTML = "";
                      }
                      if (document.getElementById('Year').value == '' || document.getElementById('Year').value == null) {
                          document.getElementById("span_ID9").innerHTML = "Select year";
                      }
                      else {
                          document.getElementById("span_ID9").innerHTML = "";

                      }
                      if (document.getElementById('ExpenseType').value == '' || document.getElementById('ExpenseType').value == null) {
                          document.getElementById("span_ID10").innerHTML = "Select expense type";
                      }
                      else {
                          document.getElementById("span_ID10").innerHTML = "";

                      }



                      if (document.getElementById('Cost').value == '' || document.getElementById('Cost').value == null) {
                          document.getElementById("span_ID11").innerHTML = "Enter cost";
                      }
                      else {
                          document.getElementById("span_ID11").innerHTML = "";
                      }
                  }




                  else {

                   
                      var values =
                           {
                               "VehicleNumber": $("#Number").find("option:selected").text(),
                               "YearsofManufacturing": $("#Year").val(),
                               "ExpenseType": $("#ExpenseType").find("option:selected").val(),
                               "Cost": $("#Cost").val()
                           }
                      var opts =
                       {
                           "closeButton": true,
                           "debug": false,
                           "positionClass": "toast-top-right",
                           "toastClass": "White",
                           "onclick": null,
                           "showDuration": "300",
                           "hideDuration": "1000",
                           "timeOut": "2000",
                           "extendedTimeOut": "1000",
                           "showEasing": "swing",
                           "hideEasing": "linear",
                           "showMethod": "fadeIn",
                           "hideMethod": "fadeOut"
                       }

                      $.ajax({
                          url: "../../Transportation/AddExpense/",
                          type: 'POST',
                          cache: false,
                          data: values,
                          traditional: true,
                          global: false,
                          success: function (result) {

                              if (result.Result === "Success") {
                                  $("#portlet-config").modal("hide");
                                  toastr.success(" Expense  added successfully", opts);
                                  setTimeout(function () { location.reload(); }, 1000);
                              }

                              if (result.Result === "Already") 
                              {        
                                  toastr.warning("Expense  already exist", opts);
                               
                              }


                          }

                      });
                      
                  }

              }
         
          </script>
                
       </body>
             </html>

Views/Transportation/ViewDetail.cshtml
@model DSRCManagementSystem.Models.ManageRoute

@{
    ViewBag.Title = "ViewDetail";
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width" />
    <link href="../../Content/Template/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css"
          rel="stylesheet" type="text/css" />
    <link href="../../Content/Template/css/font-icons/entypo/css/entypo.css" rel="stylesheet"
          type="text/css" />
    <link href="../../Content/Template/css/font-icons/entypo/css/animation.css" rel="stylesheet"
          type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic"
          id="style-resource-4" />
    <link href="../../Content/Template/css/custom.css" rel="stylesheet" type="text/css" />

    <script src="../../Content/Template/js/select2/select2.min.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(function () {
            $(".modal-body select").select2({
                minimumResultsForSearch: -1
            });

            $("#drp_VehicleNumber").select2();
        });
    </script>

</head>

<div class="modal-content">
    <div class="modal-header" style="background-color: #f0f0f1;">
        <button type="button" class="close" onclick="javascript:window.location.reload()" data-dismiss="modal" aria-hidden="true">
            ×
        </button>
        <h4 class="modal-title">View Detail</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-9" style="width: 200px; padding-top: 7px; ">
                        @Html.Label("Route Name", new { @class = "control-label" })
                        @Html.TextBoxFor(x => x.RouteName, new { @id = "txt_routeName", @name = "Route_Name", @class = "form-control", @style = "Width:350Px;Height:50px", @disabled = "disabled" })
                    </div>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-12" style="width: 200px; padding-top: 7px;">
                        @Html.Label("Vehicle Number", new { @class = "control-label" })
                        @Html.DropDownListFor(x => x.VehicleNumber, (IEnumerable<SelectListItem>)ViewData["VehicleList"], new { @id = "drp_VehicleNumber", @disabled = "disabled", @name = "Vehicle Number", @class = "form-control", @autocomplete = "off", @style = "Width:350Px;Height:50px" })
                        <span id="span_AssessmentDate" style="color: Red;"></span>
                    </div>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-3" style="width: 200px; padding-top: 7px;">
                        @Html.Label("Stops", new { @class = "control-label" })
                        @Html.ListBoxFor(x => x.stopList, Model.StopItemList, new { @id = "stopsList", @name = "Stops", @disabled = "disabled", @class = "form-control", @style = "Width:350Px;Height:120px" })
                        <span id="span_PassingScore" style="color: Red;"></span>
                    </div>
                </div>
                <br />
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            Cancel
        </button>
    </div>
</div>