Controllers/MeetingScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DSRCManagementSystem.Models;
using System.Web.SessionState;
using System.Net.Mail;
using DSRCManagementSystem;
using System.Net;
using System.Web.Security;
using System.Text.RegularExpressions;
using DSRCManagementSystem.Models.Domain_Models;
using System.Data.Objects;
using System.Data.Objects.SqlClient;
using System.Management;
using System.Globalization;
using System.Threading.Tasks;
using DSRCManagementSystem.DSRCLogic;
using System.Web.Configuration;
using System.IO;
using System.Reflection;

namespace DSRCManagementSystem.Controllers
{
    public class MeetingScheduleController : Controller
    {
        //
        // GET: /MeetingSchedule/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ProjectAgenda(int id)
        {
            DSRCManagementSystem.Models.AgandaForProject objagenda = new DSRCManagementSystem.Models.AgandaForProject();
            DSRCManagementSystemEntities1 objdb = new DSRCManagementSystemEntities1();
            string value = objdb.AgendaFeedbacks.Where(o => o.ProjectId == id).Select(o => o.Agenda).FirstOrDefault();
            if (value != null)
            {
                DateTime? date = objdb.AgendaFeedbacks.Where(o => o.ProjectId == id).Select(o => o.AgendaDate).FirstOrDefault();
                DateTime? current = System.DateTime.Now;
                TimeSpan difference = current.Value - date.Value;
                double k = difference.TotalDays;
                int j = Convert.ToInt32(k);
                if (id == 47)
                {
                    if (value != null && j >= 7)
                    {
                        value = null;
                        objagenda.ProjectAganda = value;
                    }
                    else if (value != null && j < 7)
                    {
                        objagenda.ProjectAganda = value;

                    }
                    else
                    {
                        objagenda.ProjectAganda = "";
                    }
                }
                else
                {
                    if (value != null && j >= 13)
                    {
                        value = null;
                        objagenda.ProjectAganda = value;
                    }
                    else if (value != null && j < 13)
                    {
                        objagenda.ProjectAganda = value;
                    }
                    else
                    {
                        objagenda.ProjectAganda = "";
                    }
                }
            }
            else
            {
                objagenda.ProjectAganda = "";
            }


            List<DSRCManagementSystem.Models.Historylist> objlist = new List<DSRCManagementSystem.Models.Historylist>();
            objlist = (from p in objdb.AgendaFeedbacks
                       select new DSRCManagementSystem.Models.Historylist
                       {
                           ProjectId = p.ProjectId,
                           agenda = p.Agenda,
                           feedback = p.Feedback
                       }).ToList();

            int i = objlist.Count();
            int? project = objlist.Select(o => o.ProjectId).FirstOrDefault();
            TempData["project"] = project;
            TempData["Count"] = i;

            System.Web.HttpContext.Current.Application["agenda"] = id;
            return View(objagenda);
        }

        [HttpPost]
        public ActionResult ProjectAgenda(AgandaForProject objagenda)
        {
            objagenda.UserId = Convert.ToInt32(System.Web.HttpContext.Current.Application["agenda"]);
            DSRCManagementSystemEntities1 objdb = new DSRCManagementSystemEntities1();
            var value = objdb.AgendaFeedbacks.Where(x => EntityFunctions.TruncateTime(x.FeedbackDate) == DateTime.Today.Date && x.ProjectId == objagenda.UserId).Select(x => x.Feedback).FirstOrDefault();
            var agenda = objdb.AgendaFeedbacks.Where(x => EntityFunctions.TruncateTime(x.AgendaDate) == DateTime.Today.Date && x.ProjectId == objagenda.UserId).Select(x => x.Agenda).FirstOrDefault();
            var mom = objdb.AgendaFeedbacks.Where(x => EntityFunctions.TruncateTime(x.MOMDate) == DateTime.Today.Date && x.ProjectId == objagenda.UserId).Select(x => x.MOM).FirstOrDefault();

            if (value != null && Convert.ToInt32(TempData["Count"]) == 0)
            {

                DSRCManagementSystemEntities1 db = new DSRCManagementSystemEntities1();
                DSRCManagementSystem.AgendaFeedback obj = new DSRCManagementSystem.AgendaFeedback();
                obj.Agenda = objagenda.ProjectAganda;
                obj.AgendaDate = System.DateTime.Now;
                obj.ProjectId = objagenda.UserId;
                db.AddToAgendaFeedbacks(obj);
                db.SaveChanges();
                return Json(new { Result = "Success", URL = @Url.Action("AlertPopUp", "Popup") }, JsonRequestBehavior.AllowGet);
            }

            else if (value == null && Convert.ToInt32(TempData["Count"]) != 0 && agenda != null)
            {

                DSRCManagementSystemEntities1 oho = new DSRCManagementSystemEntities1();
                var valuefed = oho.AgendaFeedbacks.Where(x => EntityFunctions.TruncateTime(x.AgendaDate) == DateTime.Today.Date && x.ProjectId == objagenda.UserId).Select(o => o).FirstOrDefault();
                valuefed.Agenda = objagenda.ProjectAganda.ToString();
                valuefed.AgendaDate = System.DateTime.Now;
                oho.SaveChanges();
                return Json(new { Result = "Success", URL = @Url.Action("AlertPopUp", "Popup") }, JsonRequestBehavior.AllowGet);
            }



            else if (value == null && Convert.ToInt32(TempData["Count"]) != 0 && agenda == null && mom != null)
            {

                DSRCManagementSystemEntities1 db = new DSRCManagementSystemEntities1();

                var val = db.AgendaFeedbacks.Where(x => EntityFunctions.TruncateTime(x.MOMDate) == DateTime.Today.Date && x.ProjectId == objagenda.UserId).Select(o => o).FirstOrDefault();
                val.ProjectId = objagenda.UserId;
                val.Agenda = objagenda.ProjectAganda.ToString();
                val.AgendaDate = System.DateTime.Now;
                db.SaveChanges();

                return Json(new { Result = "Success", URL = @Url.Action("AlertPopUp", "Popup") }, JsonRequestBehavior.AllowGet);
            }
            else if (value == null && Convert.ToInt32(TempData["Count"]) != 0 && agenda == null && mom == null)
            {

                DSRCManagementSystemEntities1 db = new DSRCManagementSystemEntities1();
                DSRCManagementSystem.AgendaFeedback obj = new DSRCManagementSystem.AgendaFeedback();
                obj.Agenda = objagenda.ProjectAganda;
                obj.AgendaDate = System.DateTime.Now;
                obj.ProjectId = objagenda.UserId;
                db.AddToAgendaFeedbacks(obj);
                db.SaveChanges();
                return Json(new { Result = "Success", URL = @Url.Action("AlertPopUp", "Popup") }, JsonRequestBehavior.AllowGet);
            }

            else if (value == null && Convert.ToInt32(TempData["Count"]) == 0)
            {
                DSRCManagementSystemEntities1 oh = new DSRCManagementSystemEntities1();
                DSRCManagementSystem.AgendaFeedback obj = new DSRCManagementSystem.AgendaFeedback();
                obj.Agenda = objagenda.ProjectAganda;
                obj.AgendaDate = System.DateTime.Now;
                obj.ProjectId = objagenda.UserId;
                oh.AddToAgendaFeedbacks(obj);
                oh.SaveChanges();
                return Json(new { Result = "Success", URL = @Url.Action("AlertPopUp", "Popup") }, JsonRequestBehavior.AllowGet);
            }
            else if (value != null && Convert.ToInt32(TempData["Count"]) != 0)
            {
                DSRCManagementSystemEntities1 obj = new DSRCManagementSystemEntities1();
                var valuefed = obj.AgendaFeedbacks.Where(x => EntityFunctions.TruncateTime(x.FeedbackDate) == DateTime.Today.Date && x.ProjectId == objagenda.UserId).Select(o => o).FirstOrDefault();
                valuefed.Agenda = objagenda.ProjectAganda.ToString();

                valuefed.AgendaDate = System.DateTime.Now;
                obj.SaveChanges();
                return Json(new { Result = "Success", URL = @Url.Action("AlertPopUp", "Popup") }, JsonRequestBehavior.AllowGet);

            }


            return View();
        }


        [HttpGet]
        public ActionResult ProjectFeedBack(int id)
        {
            DSRCManagementSystem.Models.ProjectFeedBack objagenda = new DSRCManagementSystem.Models.ProjectFeedBack();
            DSRCManagementSystemEntities1 objdb = new DSRCManagementSystemEntities1();
            string value = objdb.AgendaFeedbacks.Where(o => o.ProjectId == id).Select(o => o.Feedback).FirstOrDefault();
            if (value != null)
            {
                DateTime? date = objdb.AgendaFeedbacks.Where(o => o.ProjectId == id).Select(o => o.FeedbackDate).FirstOrDefault();
                DateTime? current = System.DateTime.Now;
                TimeSpan difference = current.Value - date.Value;
                double k = difference.TotalDays;
                int j = Convert.ToInt32(k);
                if (id == 47)
                {
                    if (value != null && j >= 7)
                    {
                        value = null;
                        objagenda.Feedback = value;
                    }
                    else if (value != null && j < 7)
                    {
                        objagenda.Feedback = value;

                    }
                    else
                    {
                        objagenda.Feedback = "";
                    }
                }

Views/MeetingSchedule/EditAttendee.cshtml
@model DSRCManagementSystem.Models.MeetingSchedule
@{
    ViewBag.Title = "Edit Attendee";
    Layout = null;   
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ProjectMeeting</title>
    <link href="../../Content/Template/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" type="text/css" />
    <link href="../../Content/Template/css/font-icons/entypo/css/entypo.css" rel="stylesheet" type="text/css" />
    <link href="../../Content/Template/css/font-icons/entypo/css/animation.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic" id="style-resource-4" />   
    <link href="../../Content/Template/css/custom.css" rel="stylesheet" type="text/css" />  
     <link href="../../Content/Template/js/select2/select2.css" rel="stylesheet" type="text/css" />
    <link href="../../Content/Template/js/select2/select2-bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="../../Content/Template/js/select2/select2.css" rel="stylesheet" type="text/css" /> 
   
     <style>
      .dropdown-menu {
    background-color: white;
}    
</style>

</head>
<body>
    <div class="modal-content">
        <div class="modal-header" style="background-color: #f0f0f1;">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×</button>
            <h4 class="modal-title">
             Edit Schedule</h4>
        </div>
            @using (Html.BeginForm("EditAttendee", "MeetingSchedule", FormMethod.Post))                      
            {
                <div class="modal-body">
                <div class="row">
                    <div class="col-md-12" style="text-align: right">
                        @Html.Label("*", new { @style = "color:#FF0000" }) Required field(s)
                        @Html.HiddenFor(x=>x.Id, new {@id="ID"})
                    </div>
                </div>
                
                 <div class="row" >
                   <div class="col-md-6">  
                     <div class="form-group">
                      @Html.Label("Attendees", new { @class = "control-label" })
                      @Html.Label("*", new { @style = "color:#FF0000" })
                      @Html.DropDownList("AttendeeId", ViewBag.Leaders as MultiSelectList, new { @id = "AttendeeId", @name = "AttendeeId", @class = "select2-container select2-container-multi select2 visible", @multiple = "multiple" })                                          
                     <span id="Attendee_Id" style="color: Red;"></span>
                      </div>
                   </div>
                 </div>

                 </div>
                  
                <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Cancel</button>
                <button type="button" id="btnAdd" class="btn btn-info" onclick="EditAttendee1()">
                    Save</button>
                </div>
            }
     </div>
       <div class="modal fade in" id="portlet-config1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="tools">
                <div id="PartialSection">
                    <div id="LoaderContent" style="height: 100%;">
                        <img src="../../Content/Template/images/finalloader.GIF" style="margin-left: 43%;
                            margin-top: 40%;" />
                    </div>
                </div>
            </div>
        </div>
    </div> 

    <script src="../../Content/Template/js/select2/select2.min.js" type="text/javascript"></script>        
   @* <script src="../../Content/Template/js/dataTables.bootstrap.js" type="text/javascript"></script>
   <script src="../../Content/Template/js/jquery.dataTables.min.js" type="text/javascript"></script>    
   <script src="../../Content/Template/js/select2/select2.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/bootbox.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/js/bootstrap.js" type="text/javascript"></script>*@
    <script src="../../Content/Template/js/toastr.js" type="text/javascript"></script>
      <script type="text/javascript">

          $(function () {
              $(".modal-body select").select2({
                  minimumResultsForSearch: -1
              });
          });

          var opts =
            {
                "closeButton": true,
                "debug": false,
                "positionClass": "toast-top-right",
                "toastClass": "White",
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "2000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }

          function EditAttendee1() {

              //$('#portlet-config1').appendTo("body").modal({ backdrop: 'static', keyboard: false });

              var errorsCount = 0;

              if ($("#AttendeeId").val() == null) {
                  errorsCount++;
                  $("#Attendee_Id").html("Select atleast one Attendee");
                  
              }
              else
                  $("#Attendee_Id").html("");

              if (errorsCount == 0) {

                  var values =
                        {
                            "Id": $("#ID").val(),
                            "Attendee": $("#AttendeeId").val().toString()
                        }

                  $.ajax({
                      url: "../../MeetingSchedule/EditAttendee/",
                      type: 'POST',
                      cache: false,
                      data: values,
                      success: function (result) {

                          if (result == "success") {


                              $("#portlet-config").modal("hide");

                              toastr.success("Attendee Edited successfully", opts);
                              //                                    setTimeout(function () { // wait 2 seconds and reload
                              //                                        window.location.reload(true);
                              //                                    }, 1000);
                              setTimeout(function () { location.reload(); }, 1000);
                          }
                          
                      }
                  });
              }

          }
    </script>
 </body>
</html>

Views/MeetingSchedule/History.cshtml
@model IEnumerable<DSRCManagementSystem.Models.History>
@{
    ViewBag.Title = "Agenda/Feedback";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@section AddToHead
{
    <link href="../../Content/Template/js/select2/select2-bootstrap.css" rel="stylesheet"
        type="text/css" />
    <link href="../../Content/Template/js/select2/select2.css" rel="stylesheet" type="text/css" />
    <link href="../../Content/Template/css/font-icons/font-awesome/css/font-awesome.min.css"
        rel="stylesheet" type="text/css" />
    <link href="../../Content/Plugins/bootstrap-datetimepicker/css/bootstrap-datepicker.css"
        rel="stylesheet" type="text/css" />
    <script src="../../Content/Plugins/bootstrap-datetimepicker/js/bootstrap-datepicker.js"
        type="text/javascript"></script>
    <script src="../../Content/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/bootbox.min.js" type="text/javascript"></script>

     <style>
      .dropdown-menu {
    background-color: white;
}    
</style>

}
@{
    int SNO = 1;
    
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddUser</title>
    <style type="text/css">
        textarea
        {
            resize: none;
        }
    </style>
</head>
<body>
    <ol class="breadcrumb bc-3">
        <li class="active"><strong>View Agenda/Feedback</strong></li>
    </ol>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default panel-shadow" data-collapsed="0">
                <!-- panel head -->
                <div class="panel-heading">
                    <div class="panel-title" color="White">
                       View Agenda/Feedback </div>
                </div>
                <div>
                  @*<div class="row" >
                  <div class="col-md-3">
                    <div class="form-group">
                       <label class="col-sm-3 control-label">
                   &nbsp;&nbsp; Week  @Html.Label(" ", new { @style = "color:#FF0000" })                
                     </label> 
                      @Html.DropDownList("Week", ViewBag.Week as SelectList, new { @id = "Week", @name = "Week", @class = "form-control" })
                     <span id="span_ID9" style="color: Red;"></span>
                   </div>
                   </div>
                </div>  *@

                 </div>
                <!-- panel body -->
                <div class="panel-body">
                    @using (Html.BeginForm("History","MeetingSchedule", FormMethod.Post))
                    { 
                        <table class="table table-bordered datatable" id="tblMeeting">
                            <thead>
                                <tr>
                                    <th style="text-align:center;">
                                        S.No
                                    </th>
                                    <th style="text-align:center;">
                                        @Html.DisplayNameFor(i => i.Date)
                                    </th>
                                     <th style="text-align:center;">
                                        @Html.DisplayNameFor(i => i.Agenda)
                                    </th>
                                   @* <th>
                                        @Html.DisplayNameFor(i => i.Week)
                                    </th>
                                   *@
                                  
                                    <th style="text-align:center;">
                                        @Html.DisplayName("Feedback")
                                    </th>
                                    <th style ="text-align:center;">
                                    @Html.DisplayName("MOM")
                                    </th>
                                </tr>
                            </thead>
                            @{
                      
                        foreach (var item in Model)
                        {
                          
                                <tr>
                                    <td style="text-align: center;">
                                        @(SNO++)
                                    </td>
                                  <td style="width:1200px;word-wrap:break-word;word-break:break-all;text-align:center;">
                                        @Html.DisplayFor(modelItem => item.Date)
                                    </td>
                                    <td style="width:2000px;word-wrap:break-word;word-break:break-all;text-align:left;">
                                         @Html.Raw(Html.Encode(item.Agenda ?? string.Empty).Replace("\n", "<br />"))
                                    </td>
                                  <td style="width:1800px;word-wrap:break-word;word-break:break-all;text-align:left;">
                                       @Html.Raw(Html.Encode(item.Feedback ?? string.Empty).Replace("\n", "<br />"))
                                    </td>
                                     <td style="width:1800px;word-wrap:break-word;word-break:break-all;text-align:left;">
                                        @Html.Raw(Html.Encode(item.MOM ?? string.Empty).Replace("\n", "<br />"))
                                    </td>
                                </tr>
                       

                        }
                            }
                        </table>

                            
                           
                    }
                </div>
                <div class="modal-footer">
            <button type="button" class="btn btn-default"  onclick="@("window.location.href='" + @Url.Action("MeetingSchedule", "MeetingSchedule") + "'");" ) >
                Back
            </button>
        </div>
            </div>
        </div>
    </div>
    <div class="modal fade in" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="tools">
                <div id="PartialSection">
                </div>
            </div>
        </div>
    </div>
  <script src="../../Content/Template/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="../../Content/Template/js/dataTables.bootstrap.js" type="text/javascript"></script>
    <script src="../../Content/Template/js/select2/select2.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/bootbox.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/js/bootstrap.js" type="text/javascript"></script>
    <script src="../../Content/Template/js/toastr.js" type="text/javascript"></script>
 
<script type="text/javascript">

    jQuery(document).ready(function ($) {

        var columnDefs;
        //        if ($("aTargets")[6]) {
        //            columnDefs = [{ bSortable: false, 'aTargets': [4] }, { bSortable: false, 'aTargets': [5] }, { bSortable: false, 'aTargets': [6]}];
        //        } else {
        //            columnDefs = [{ bSortable: false, 'aTargets': [4] }, { bSortable: false, 'aTargets': [5]}];
        //        }
        $("#tblMeeting").dataTable({
            "sPaginationType": "bootstrap",
            "aLengthMenu": [[10, 15, 20, 25, -1], [10, 15, 20, 25, "All"]]
            //            "bStateSave": false,
            //            "columnDefs": columnDefs
        });
        $(".dataTables_wrapper select").select2({
            minimumResultsForSearch: -1
        });
        $('thead>tr>th').css('text-align', 'center');
    });
    </script>
        
</body>
</html>

Views/MeetingSchedule/MOM.cshtml
@model DSRCManagementSystem.Models.ProjectMom
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ProjectMom</title>
    <link href="../../Content/Template/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css"
        rel="stylesheet" type="text/css" />
    <link href="../../Content/Template/css/font-icons/entypo/css/entypo.css" rel="stylesheet"
        type="text/css" />
    <link href="../../Content/Template/css/font-icons/entypo/css/animation.css" rel="stylesheet"
        type="text/css" />

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic"
        id="style-resource-4" />
    @*<link href="../../Content/Template/css/neon.css" rel="stylesheet" type="text/css" />*@
    <link href="../../Content/Template/css/custom.css" rel="stylesheet" type="text/css" />
    @*<script src="../../Content/Plugins/bootstrap-datetimepicker/js/en-gb.js" type="text/javascript"></script>*@
    <script src="../../Content/Plugins/bootstrap-datetimepicker/js/moment.js" type="text/javascript"></script>
 @*   <script src="../../Content/Plugins/bootstrap-datetimepicker/js/bootstrap-datepicker.js"
        type="text/javascript"></script>*@
@*    <link href="../../Content/Plugins/bootstrap-datetimepicker/css/bootstrap-datepicker.css"
        rel="stylesheet" type="text/css" />*@
    <script src="../../Content/Plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"
        type="text/javascript"></script>
    <link href="../../Content/Plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css"
        rel="stylesheet" type="text/css" />
     <style>
      .dropdown-menu {
    background-color: white;
}    
</style>

</head>
<body>
    <div class="modal-content">
        <div class="modal-header" style="background-color: #f0f0f1;">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×</button>
            <h4 class="modal-title">
            Add Project MOM</h4>
        </div>
 
     <div class="modal-body">

            @using (Html.BeginForm("MOM", "MeetingSchedule", FormMethod.Post))
            {
                <div class="row">
                    <div class="col-md-12" style="text-align: right">
                        @Html.Label("*", new { @style = "color:#FF0000" }) Required field(s)
                    </div>
                </div>
                
                 <div class="row">
                   
                    <div class="col-md-3">  
                     <div class="form-group">
                      @Html.Label("Project MOM", new { @class = "control-label" })
                      @Html.Label("*", new { @style = "color:#FF0000" })                    
                     <span id="span_ID8" style="color: Red;"></span>
                      </div>
                      </div>

                        <div class="col-md-12">  
                     <div class="form-group">                    
                     @Html.TextAreaFor(m => m.ProjectMOM, new { @class = "form-control", @id = "ProjectAganda", @maxlength = 1500, @cols = 120, @rows = 12, @wrap = "hard" })
                     <span id="span_ID10" style="color: Red;"></span>
                      </div>
                      </div>

                    </div>
                
                   }
                    
                </div>  
                                 
               

            
           
             <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
                Cancel
            </button>
            <button type="button" id="btnAdd" class="btn btn-info"  onclick='Agenda()'>
                Save
            </button>
        </div>
     
              </div>     
                
     <div class="modal fade in" id="portlet-config1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="tools">
                <div id="PartialSection">
                    <div id="LoaderContent" style="height: 100%;">
                        <img src="../../Content/Template/images/finalloader.GIF" style="margin-left: 43%;
                            margin-top: 40%;" />
                    </div>
                </div>
            </div>
        </div>
    </div> 
           <script src="../../Content/JS/ToasterAlert.js" type="text/javascript"></script>
             <script type="text/javascript">

                 function Agenda() {

                     if (document.getElementById('ProjectAganda').value == '') {

                         document.getElementById("span_ID10").innerHTML = "Enter Project MOM";
                     }
                     else {
                         $('#portlet-config1').appendTo("body").modal({ backdrop: 'static', keyboard: false });

                         $("#ProjectAganda").val();
                         var submitForm = true;

                         if (submitForm == true) {

                             var values =
                        {
                            "ProjectMOM": $("#ProjectAganda").val()

                        }
                             var opts =
                      {
                          "closeButton": true,
                          "debug": false,
                          "positionClass": "toast-top-right",
                          "toastClass": "White",
                          "onclick": null,
                          "showDuration": "300",
                          "hideDuration": "1000",
                          "timeOut": "2000",
                          "extendedTimeOut": "1000",
                          "showEasing": "swing",
                          "hideEasing": "linear",
                          "showMethod": "fadeIn",
                          "hideMethod": "fadeOut"
                      }

                             $.ajax({
                                 url: "../../MeetingSchedule/MOM/",
                                 type: 'POST',
                                 cache: false,
                                 data: values,
                                 global: false,
                                 success: function (result) {
                                     if (result.Result === "Success") {

                                         $("#portlet-config").modal("hide");

                                         toastr.success("Project MOM added successfully", opts);
                                         setTimeout(function () { location.reload(); }, 1000);
                                     }
                                 }

                             });
                         }
                     }
                 }

             </script>
                
            </body>
</html>