Models/TimeEntry.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DSRCManagementSystem.Models
{
    public class TimeEntry
    {
        public HttpPostedFileBase excelFile { get; set; }

        public string ErrorSuccessMessage { get; set; }

        public string EmpID { get; set; }
        public DateTime Date { get; set; }

        public List<SelectListItem> BranchList { get; set; }
       
        public int BranchID { get; set; }
        public string BranchName { get; set; }
    }

   
}

Controllers/TimeEntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DSRCManagementSystem.Models;
using System.IO;
using DSRCManagementSystem.DSRCLogic;
using Utilities;
using System.Net.Mail;
using System.Data;
using System.Data.Objects;
using DSRCManagementSystem.Controllers;
using System.Web.Configuration;
using System.Threading.Tasks;


namespace DSRCManagementSystem.Models
{
    public class TimeEntryController : Controller
    {
        //
        // GET: /Attendance/UploadAttendance
        DSRCManagementSystemEntities1 db = new DSRCManagementSystemEntities1();
        private static TimeZoneInfo INDIAN_ZONE = TimeZoneInfo.FindSystemTimeZoneById("India Standard Time");
        DsrcMailSystem.MailSender AppValue = new DsrcMailSystem.MailSender(); 
        // [DSRCAuthorize(Roles = "Attendant")]
        public ActionResult UploadAttendance()
        {
            ViewBag.Lbl_branch = CommonLogic.getLabelName(1).ToString();
            TimeEntry model = new TimeEntry();
            try
            {
                List<SelectListItem> Branches = GetBranches();
                Branches.Insert(0, new SelectListItem { Text = "--Select--", Value = "0" });
                model.BranchList = Branches;
            }
            catch (Exception Ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                ExceptionHandlingController.ExceptionDetails(Ex, actionName, controllerName);
            }
            return View(model);
        }

        //[HttpPost]
        ////[DSRCAuthorize(Roles = "Attendant")]
        //public ActionResult UploadAttendance(TimeEntry model)
        //{

        //    int userId = Convert.ToInt32(Session["UserID"]);
        //    string folderPath = Server.MapPath("~/FileManager/" + userId + Session.SessionID + "/" + userId + DateTime.Now.ToString("dd-MM-yyyy hh-MM-ss"));
        //    var Excelfile = model.excelFile;
        //    List<SelectListItem> Branches = GetBranches();
        //    Branches.Insert(0, new SelectListItem { Text = "--Select--", Value = "0" });
        //    model.BranchList = Branches;
        //    // string errorMessage = string.Empty;
        //    if (model.BranchID != 0)
        //    {
        //        if (Excelfile != null)
        //        {
        //            //var Extension = Excelfile.FileName.Substring(Excelfile.FileName.LastIndexOf(".") + 1);
        //            var Extension = Path.GetExtension(Excelfile.FileName);
        //            if ((Extension == ".xlsx") || Extension == ".xls")
        //            {
        //                if (!Directory.Exists(folderPath))
        //                    Directory.CreateDirectory(folderPath);
        //                var fileName = Path.GetFileName(Excelfile.FileName);
        //                var path = Path.Combine(folderPath, fileName);
        //                Excelfile.SaveAs(path);
        //                ExcelUtility objExcelUtility = new ExcelUtility();
        //                try
        //                {
        //                   // objExcelUtility.ImportExcelToDatabase(path, model.BranchID);
        //                    communicationHelper.DeleteDuplicateTimeEntry();
        //                    model.ErrorSuccessMessage = "Excel file uploaded successfully.";
        //                    SendMail();
        //                }
        //                catch (Exception ex)
        //                {
        //                    ExceptionHandlingController.ExceptionDetails(ex);
        //                    model.ErrorSuccessMessage = "Error: " + ex.Message;
        //                    return View(model);
        //                }
        //            }
        //            else
        //            {
        //                model.ErrorSuccessMessage = "Please upload excel files only.";
        //            }
        //        }
        //        else
        //        {
        //            model.ErrorSuccessMessage = "Please upload the excel file.";
        //        }
        //    }
        //    else
        //    {
        //        model.ErrorSuccessMessage = "Please select branch";
        //    }
        //    return View(model);
        //}

        //private void SendMail(int BranchID)
        //{
          
        //        string ServerName = WebConfigurationManager.AppSettings["SeverName"];
        //        DateTime indianTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, INDIAN_ZONE);
        //        var BranchName = db.Master_Branches.Where(x => x.BranchID == BranchID).Select(o => o.BranchName).FirstOrDefault();
        //        if (ServerName  != "http://win2012srv:88/")
        //        {
        //            MailMessage mail = new MailMessage();
        //            List<string> MailIds = db.TestMailIDs.Select(o => o.MailAddress).ToList();

        //            string EmailAddres = "";

        //            //foreach (string mails in MailIds)
        //            //{
        //            //    EmailAddres += mails + ",";
        //            //}

        //            for (int i = 0; i < MailIds.Count(); i++)
        //            {
        //                if (i != MailIds.Count() - 1)
        //                {
        //                    EmailAddres += MailIds[i] + ",";
        //                }
        //                else
        //                {
        //                    EmailAddres += MailIds[i];
        //                }

        //            }


        //            mail.To.Add(EmailAddres);
        //            mail.From = new MailAddress("TestMail@dsrc.co.in");
        //            mail.Subject = "Test-Regarding Attendance upload";
        //            var company = db.Master_ApplicationSettings.Where(x => x.AppKey == "Company Name").Select(o => o.AppValue).FirstOrDefault();

        //            mail.Body = "Thanks for uploading Attendance on" + " " + indianTime + " " + "<br>" + "for" + BranchName + " " + "branch" + "<br/><br/>This email has been automatically generated.</br>Please do not reply to this email address as all responses are directed to an unattended,<br/>mailbox, and you will not receive a response</p><br/><br/><p style=font-size:15px>Thanks,<br/>" + company + "Management Portal</p>";
        //            mail.IsBodyHtml = true;
        //            SmtpClient smtp = new SmtpClient();
        //            smtp.Host = "192.168.4.101";
        //            smtp.Port = 2525;
        //            smtp.UseDefaultCredentials = false;
        //            smtp.Credentials = new System.Net.NetworkCredential
        //            ("prasanthk@dsrc.co.in", "dsrc1234");// Enter senders User name and password                               
        //            smtp.EnableSsl = false;
        //            smtp.Send(mail);
        //        }
        //        else
        //        {
        //            MailMessage mail = new MailMessage();
        //            mail.To.Add("prasanthk@dsrc.co.in , umapathy@dsrc.co.in");
        //            mail.From = new MailAddress("HRMS@dsrc.co.in");
        //            mail.Subject = "Test-Regarding Attendance upload";
        //            var company = db.Master_ApplicationSettings.Where(x => x.AppKey == "Company Name").Select(o => o.AppValue).FirstOrDefault();
        //            mail.Body = "Thanks for uploading Attendance on" + " " + indianTime + " " + "<br/><br/>This email has been automatically generated.</br>Please do not reply to this email address as all responses are directed to an unattended,<br/>mailbox, and you will not receive a response</p><br/><br/><p style=font-size:15px>Thanks,<br/>" + company + " Management Portal</p>";
        //            mail.IsBodyHtml = true;
        //            SmtpClient smtp = new SmtpClient();
        //            smtp.Host = "192.168.4.101";
        //            smtp.Port = 2525;
        //            smtp.UseDefaultCredentials = false;
        //            smtp.Credentials = new System.Net.NetworkCredential
        //            ("Mubarakbasha.S@dsrc.co.in", "dsrc12345");// Enter senders User name and password                               
        //            smtp.EnableSsl = false;
        //            smtp.Send(mail);
        //        }
        //    }
        
        //[HttpPost]
        //public FileResult SampleAttendanceFile()
        //{
        //    string filename = Server.MapPath(Url.Content("~/SampleAttendanceFile/Access 1st Mar to 31st Mar 2015.xls"));
        //    string contentType = "application/vnd.ms-excel";
        //    //var temp = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "SampleAttendanceFile");

        //    return new FilePathResult(filename, contentType) { FileDownloadName = "Sample_Attendance_File.xls" };
        //}

        //public ActionResult EnterAttendance()
        //{
        //    return View();
        //}

        
        //[DSRCAuthorize(Roles = "Attendant")]
        //public ActionResult EnterAttendance()
        //{
            //EditTimeEntry ObjPM = new EditTimeEntry();
            //ObjPM.IsSubmit = false;  
            ////SelectList EmpList = (SelectList)GetNames(1).Data;
            ////ObjPM.EmployeeList = EmpList.Select(x => new SelectListItem { Text = x.Text, Value = x.Value }).ToList();
            //ObjPM.EmployeeList = GetNames(1);
            //ObjPM.BranchList = GetBranches();
            //ObjPM.Date = null;
            //ObjPM.EmployeeId = null;

            //return View( ObjPM);
       // }

        //[HttpPost]
        ////[DSRCAuthorize(Roles = "Attendant")]
        //public ActionResult EnterAttendance(EditTimeEntry Model)
        //{
        //    DSRCManagementSystemEntities1 DBHRMS = new DSRCManagementSystemEntities1();

Views/TimeEntry/EditTime.cshtml
@model DSRCManagementSystem.Models.EditTimeEntry
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
     <script src="../../Content/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="../../Content/bootstrap/js/bootstrap.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Attendance Entry</title>

    <style>
       .dropdown-menu {
    background-color: white;
}        
 </style> 

    </head>
    <body>
     <div class="modal-content">
        <div class="modal-header" style="background-color: #f0f0f1;">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×</button>
            <h4 class="modal-title">
                Attendance Entry</h4>
        </div>
        @using (Html.BeginForm("EditTime", "TimeEntry", FormMethod.Post))
            { 
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12" style="text-align: right">
                    @Html.Label("*", new { @style = "color:#FF0000" }) Required field(s)
                </div>
            </div>
             <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                         @Html.Label("Employee ID", new { @class = "control-label" })                        
                        @Html.TextBoxFor(x => x.EmployeeId, new { @id = "EmployeeId", @name = "EmployeeId", @class = "form-control", @placeholder = "EmployeeId", @autocomplete = "off", @maxlength = 100, @disabled = "disabled" })
                        @Html.HiddenFor(x => x.UserID)
                        @Html.HiddenFor(x => x.BranchID, new { @id = "BranchID" })
                      @* @Html.ValidationMessageFor(X => X.EmployeeName, null, new { @style = "color:red" })*@
                    </div>
                    </div>
                    </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => x.EmployeeName, new { @class = "control-label" })                      
                        @Html.TextBoxFor(x => x.EmployeeName, new { @id = "EmployeeName", @name = "EmployeeName", @class = "form-control", @placeholder = "EmployeeName", @autocomplete = "off", @maxlength = 100, @disabled = "disabled" })
                      @*  @Html.ValidationMessageFor(X => X.EmployeeName, null, new { @style = "color:red" })*@
                       
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Date, new { @class = "control-label" })                      
                        @Html.TextBoxFor(x => x.Date, new { @id = "Date", @name = "Date", @class = "form-control", @placeholder = "Date", @autocomplete = "off", @maxlength = 100, @disabled = "disabled" })
                      @*  @Html.ValidationMessageFor(X => X.EmployeeName, null, new { @style = "color:red" })*@
                    </div>
                </div>
            </div>
           
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group datetimepickerTime1">
                         @Html.Label("In Time", new { @class = "control-label" })     
                        @Html.Label("  *", new { @style = "color:red;font-weight:bold;" })
                        @Html.TextBoxFor(x => x.InTime, new { @id = "InTime", @name = "InTime", @class = "form-control", @placeholder = "In Time", @autocomplete = "off", @maxlength = 5 })
                        @Html.ValidationMessageFor(X => X.InTime, null, new { @style = "color:red" })
                        <span id="span_InTime" style="color: Red;"></span>
                    </div>
                    <div class="form-group datetimepickerTime2">
                        @Html.Label("Out Time", new { @class = "control-label" })     
                        @Html.Label("  *", new { @style = "color:red;font-weight:bold;" })
                        @Html.TextBoxFor(x => x.OutTime, new { @id = "OutTime", @name = "OutTime", @class = "form-control", @placeholder = "Out Time", @autocomplete = "off", @maxlength = 5 })
                        @Html.ValidationMessageFor(X => X.OutTime, null, new { @style = "color:red" })                  
                        <span id="span_OutTime" style="color: Red;"></span>
                    </div>
                </div>
                </div>
                </div>
                }
 <div class="modal-footer">
  <button type="button" id="btnAdd" class="btn btn-info" onclick="UpdateEnrtyTime()" >
                Save
            </button>
            <button type="button" class="btn btn-default" data-dismiss="modal" >
                Cancel
            </button>
            
            </div>   
         </div>         
     <script type="text/javascript">
        
       
         $(document).ready(function () {
             $(".datetimepickerTime1").datetimepicker
           ({
               format: 'LT',
               pickDate: false
           });
         });

         $(document).ready(function () {
             $(".datetimepickerTime2").datetimepicker
           ({
               format: 'LT',
               pickDate: false
           });
       });
       
           $('#InTime').keypress(function (e) {
               var regex = new RegExp("^[0-9\\:\\s]+$");
               var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
               if (regex.test(str)) {

                   return true;
               }
               $("#span_InTime").html("Enter Valid In Time").show();
               return false;
           });

           $('#OutTime').keypress(function (e) {
               var regex = new RegExp("^[0-9\\:\\s]+$");
               var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
               if (regex.test(str)) {

                   return true;
               }
               $("#span_OutTime").html("Enter Valid Out Time").show();
               return false;
           });


         function UpdateEnrtyTime() {
             if (document.getElementById('InTime').value == '' || document.getElementById('OutTime').value == '') {

                 if (document.getElementById('InTime').value == '')
                     document.getElementById("span_InTime").innerHTML = "Enter In Time";
                 else
                     document.getElementById("span_InTime").innerHTML = "";
                 if (document.getElementById('OutTime').value == '')
                     document.getElementById("span_OutTime").innerHTML = "Enter Out Time ";
                 else {
                     document.getElementById("OutTime").innerHTML = "";
                 }
             }

             //             else {
             //                 var submitForm = true;
             //             }

             //             if (submitForm === true) {

             else {





                 var fromTime = $("#InTime").val();
                 var endTime = $("#OutTime").val();
                 var hour1 = parseInt(fromTime.substring(0, 2));
                 var hour2 = parseInt(endTime.substring(0, 2));

                 if (hour1 < hour2) {

                    // if (hour1 == 12 && hour2 == 1) {

                         var values =
                    {
                        "UserId": $("#UserId").val(),
                        "BranchID":$("#BranchID").val(),
                        "EmployeeName": $("#EmployeeName").val(),
                        "Date": $("#Date").val(),
                        "EmployeeId": $("#EmployeeId").val(),
                        "InTime": $("#InTime").val().trim(),
                        "OutTime": $("#OutTime").val().trim()
                    }

                         var opts = {
                             "closeButton": true,
                             "debug": false,
                             "positionClass": "toast-top-right",
                             "toastClass": "White",
                             "onclick": null,
                             "showDuration": "300",
                             "hideDuration": "1000",
                             "timeOut": "3000",
                             "extendedTimeOut": "1000",
                             "showEasing": "swing",
                             "hideEasing": "linear",
                             "showMethod": "fadeIn",
                             "hideMethod": "fadeOut"
                         }
                     }

                     $.ajax({
                         url: "../../TimeEntry/EditTime",
                         type: 'POST',
                         cache: false,
                         data: values,
                         success: function (result) {


                             if (result == true) {
                                 $("#portlet-config").modal("hide");                                             
                                 toastr.success("User Time has been updated successfully", opts);
                                 setTimeout(function () {                                     
                                     window.location = window.location;
                                 }, 1000);
                             }
                             else {
                                 document.getElementById("span_OutTime").innerHTML = "OutTime Must Greater Than The InTime ";
                                 var submitForm = false;
                             }

                         }

                     });
                 }
             }
         
                   

                   </script>

            </body>
            </html>

Views/TimeEntry/EnterAttendance.cshtml
@model DSRCManagementSystem.Models.EditTimeEntry
@{
    ViewBag.Title = "Enter Attendance";
    //Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    Layout = null;
}

<!DOCTYPE html>

@section AddToHead
    {
    <style>
        #Date
        {
            height:41px;
            }
        th
        {
            background-color: white;
            color: black;
                            
                           
            text-align: center;
        }
    </style>

    <style>
       .dropdown-menu {
    background-color: white;
}        
 </style> 

    <script src="../../Content/JS/date.js" type="text/javascript"></script>
    <script src="../../Content/Plugins/bootstrap-datetimepicker/js/moment.js" type="text/javascript"></script>
    <script src="../../Content/Plugins/bootstrap-datetimepicker/js/en-gb.js" type="text/javascript"></script>
    }
@{
    int SNO = 1;
}

<br />
<div class="row" style="height: 800px; overflow: auto;">
    <div class="col-md-12">
        <div class="panel panel-default panel-shadow" data-collapsed="0">
            <!-- panel head -->
            <div class="panel-heading">
                <div class="panel-title" color="White">
                    Attendance Entry</div>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                @using (Html.BeginForm("Attendance", "TimeEntry", FormMethod.Post))
                {
                    
                    
                    <div class="form-group">
                      <div class="row">
                        <div class="form-group">                            
                            <div class="col-md-3">
                                @Html.Label("Branch",(string)ViewBag.Lbl_branch, new { @class = "control-label" })
                                @Html.DropDownListFor(x => x.BranchID, Model.BranchList, new { @class = "select2", @id = "BranchID", @onchange = "fnBranchchange()" })
                            </div>
                                                        
                            <div class="col-md-3">
                                @Html.Label("All Members", new { @class = "control-label" })
                                @Html.DropDownListFor(x => x.EmployeeId, Model.EmployeeList, new { @class = "select2", @id = "EmployeeId", @onchange = "fnUserchange()" })
                            </div>                        
                                                        
                            <div class="col-md-3">                     
                                @Html.Label("Date", new { @class = "control-label" })
                                @Html.TextBoxFor(x => x.Date, new { @id = "Date", @class = "form-control datetimepicker", @placeholder = "Date", @autocomplete = "off", @onchange = "fnUserchange()" })                            
                            </div>

                        <div class="col-md-3" style="padding-top:28px;" >
                            <button type="submit" name="btn_Submit" class="btn btn-info btn-icon" id="search">
                                Search<i class="entypo-search"></i>
                            </button>
                        </div>
                        </div>
                      </div>
                    </div>
                    if (Model.IsSubmit)
                    {
                        Model.IsSubmit = false;
                   
                    <div class="modal-body">
                        @if (Model.IsRecordAvail)
                        {
                            <table id="tblEmployeeLeaveBalanceDetails" class="table table-bordered datatable">
                           
                                <tr>
                                    <th style="font-weight:bold;">
                                        Employee ID
                                    </th>
                                    <th style="font-weight:bold;">
                                        Employee Name
                                    </th>
                                    <th style="font-weight:bold;">
                                        Date
                                    </th>
                                    <th style="font-weight:bold;">
                                        In Time
                                    </th>
                                    <th style="font-weight:bold;">
                                        Out Time
                                    </th>
                                    <th>
                                    </th>
                                </tr>
                               
                                <tbody>
                                    <tr>
                                        <td>
                                            @Model.EmployeeId
                                            @Html.HiddenFor(modelItem => Model.UserID)
                                        </td>
                                        <td>
                                            @Model.EmployeeName
                                        </td>
                                        <td align="center">
                                            @Model.Date.Value.ToString("dd/MM/yyyy")
                                        </td>
                                        <td align="center">
                                            @Model.InTime
                                        </td>
                                        <td align="center">
                                            @Model.OutTime
                                        </td>
                                        <td>
                                            <a>
                                                <button type="button" class="btn btn-info btn-icon icon-left" onclick='EditTime("@Model.EmployeeId","@Model.Date.Value.ToString("dd/MM/yyyy")")' >
                                                    <i class="entypo-info"></i>Edit
                                                </button>
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        }
                        else
                        {
                             <div style="text-align: center">
                                   <h4>
                                       No Record Found</h4>
                             </div>
                        }
                    </div>
                            
                    }

                }
            </div>
        </div>
    </div>
</div>
<div class="modal fade in" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="tools">
            <div id="PartialSection">
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    function fnUserchange() {
        var selectedId = $('#EmployeeId').val();
        var date = $('#Date').val();
        if (selectedId == 0 || date == "") {

            $('#search').hide();
        }
        else {
            $('#search').show();
        }
    }

    function fnBranchchange() {

//                var selectedId =0;
//                var date = "";

//                $('#Date').val("");

//                if (selectedId == 0 || date == "") {

//                    $('#search').hide();
//                }
//                else {
//                    $('#search').show();
        //                }

              $('#search').hide();

                var BranchId = $('#BranchID').find("option:selected").prop("value");

                var url2 = '@Url.Action("GetAvailEmployees")';

                $.get(url2, { BranchID: BranchId }, function (data) {

                    var items = [];
                    items.push("");
                    items.push("<option value=0>--Select--</option>");

                    $.each(data, function () {
                        items.push("<option value=" + this.Value + ">" + this.Text + "</option>");

                    });
                    $("#EmployeeId").html(items.join(' '));
                    $("#EmployeeId").select2();
                });
    }

    $(document).ready(function () {
        fnUserchange();
        $("#Date", "#EmployeeId").change(function () { fnUserchange() });
    });
</script>
@section scripts
{
    <script src="../../Content/Template/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="../../Content/Template/js/dataTables.bootstrap.js" type="text/javascript"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            $(".datetimepicker").datepicker({
                format: 'dd/mm/yyyy',
                todayHighlight: true,
                daysOfWeekDisabled: [0, 6],
                autoclose: true,

            })
            $(".date-picker").datepicker("setDate", "");
              var table = $("#tblEmployeeLeaveBalanceDetails").dataTable({
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "sPaginationType": "bootstrap" 
                          });
            $(".dataTables_wrapper select").select2({
                minimumResultsForSearch: -1
            });
           $('thead>tr>th').css('text-align', 'center');
        });
    </script>
    <script type="text/javascript">
        var opts = {
            "closeButton": true,
            "debug": false,
            "positionClass": "toast-top-right",
            "toastClass": "White",
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "1000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        function EditTime(employeeId, date) {
          
            var BranchId = $("#BranchID").find("option:selected").prop("value");
        
            $.ajax({ url: "../../TimeEntry/EditTime/",
                type: 'GET', cache: false,
                data: { EmployeeId: employeeId, Date: date, BranchId: BranchId },
                success: function (result) {
                    $('#PartialSection').html(result);
                    $('#portlet-config').appendTo("body").modal('show');
                }
            });
        }
    </script>
}